FROM nohkwangsun/spark-base:latest

WORKDIR /

RUN mkdir temp
ADD local.conf temp/local.conf
ADD local.sh temp/local.sh
ADD shiro.ini temp/shiro.ini

RUN wget https://dl.bintray.com/sbt/native-packages/sbt/0.13.9/sbt-0.13.9.tgz && \
    tar xzf sbt-0.13.9.tgz

ENV PATH $PATH:/sbt/bin 

RUN apt-get update && apt-get install -y ssh && \
    sed s/'PermitRootLogin without-password'/'PermitRootLogin yes'/g /etc/ssh/sshd_config > .temp && mv .temp /etc/ssh/sshd_config && \
    echo 'StrictHostKeyChecking no' >> /etc/ssh/ssh_config && \
    echo 'root:1234' | chpasswd && \
    service ssh restart && \
    git clone -b v0.6.1 https://github.com/spark-jobserver/spark-jobserver.git --depth 1 && \
    cd spark-jobserver && \
    git checkout -b v0.6.1 && \
    cp /temp/* config/. && \
#    bin/server_deploy.sh local
    ls

EXPOSE 8090

CMD ./server_start.sh && \
    sleep 2 && \
    tail -f logs/spark-job-server.log
