# nohkwangsun/spark-hdfs-worker-controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-worker
  name: spark-worker
spec:
  replicas: 2
  selector:
    name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: nohkwangsun/spark-hdfs-worker:latest
        name: spark-worker
        env:
        - name: SPARK_WORKER_MEMORY
          value: 1g
        ports:
        - containerPort: 7078
          hostPort: 7078
          protocol: TCP
        - containerPort: 50010
          hostPort: 50010
          protocol: TCP
        - containerPort: 50020
          hostPort: 50020
          protocol: TCP
